# Generated by Django 3.0 on 2019-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('overview', models.TextField(blank=True, default='Small description', max_length=250)),
                ('description', models.TextField(blank=True, default='Detailed description', max_length=1500)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
                ('added date', models.DateField(auto_now=True)),
                ('added time', models.TimeField(auto_now=True)),
                ('slug', models.SlugField(default='thisisaslug', unique=True)),
            ],
        ),
    ]
